# Generated by Django 6.0 on 2026-01-03 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('matricula', models.CharField(max_length=20, unique=True)),
                ('idade', models.IntegerField()),
                ('serie', models.CharField(max_length=50)),
                ('turno', models.CharField(max_length=20)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
    ]
